# Generated by Django 2.2.16 on 2022-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='categories',
            name='title',
            field=models.CharField(default='Музыка', max_length=35, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
