# Generated by Django 2.2.16 on 2022-07-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите Username', max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
