# Generated by Django 2.2.16 on 2022-04-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220331_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
