# Generated by Django 2.2.16 on 2022-04-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220404_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='work',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='titlesgenres',
            old_name='work',
            new_name='title',
        ),
    ]
